language: generic

compiler:
    - g++

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt58-trusty'
    packages:
      - g++
      - gettext
      - intltool
      #- libqt4-dev
      - qt58base
      - qt58svg
      - qt58webengine
      - qt58tools 
      - autoconf
      - automake
      - libexiv2-dev
      - libalglib-dev
      - libboost-all-dev
      - mesa-common-dev
      - libfftw3-dev
      - libtiff5-dev
      - libpng12-dev
      - libopenexr-dev
      - libgsl0-dev
      - libcfitsio3-dev

#env:
#    - PATH="/opt/qt58/bin:$PATH"
#    - LD_LIBRARY_PATH="/opt/qt58/lib:$LD_LIBRARY_PATH"

before_script:
    - cat /opt/qt58/bin/qt58-env.sh
    - /opt/qt58/bin/qt58-env.sh
    - git clone https://github.com/LuminanceHDR/LuminanceHDR.git
    - cd LuminanceHDR
    - mkdir -p build
    - cd build
    - export PKG_CONFIG_PATH=/zyx/lib/pkgconfig:${PKG_CONFIG_PATH}
    - export LD_LIBRARY_PATH=/zyx/lib:${LD_LIBRARY_PATH}
    - git clone https://github.com/LibRaw/LibRaw.git
    - cd LibRaw
    - autoreconf --install
    #- automake --add-missing
    #- autoconf
    - pwd
    - ls
    - ./configure --prefix=/usr
    - make -j2
    - sudo make install
    - cd ..
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/zyx ..
    #- make DESTDIR=$TRAVIS_BUILD_DIR/appdir -j2 install
    - make -j2 && sudo make install
    - cd ..

script:
    - mkdir -p appimage
    - cp $TRAVIS_BUILD_DIR/appimage.sh appimage
    - bash appimage/appimage.sh

after_success:
    - cd $TRAVIS_BUILD_DIR
    - pwd
    - ls -lh
    - ls -lh out/* # Assuming you have some files in out/ that you would like to upload
    #- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
    - bash  ./upload_rotate.sh "continuous" out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

