language: generic
os: linux
dist: trusty
compiler: g++
sudo: required
services: docker


before_script:
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  - travis_wait 120 sleep infinity & sudo docker pull photoflow/docker-trusty-appimage-base
  - git clone https://github.com/LuminanceHDR/LuminanceHDR.git
  - rm -rf LuminanceHDR/ci
  - cp -a ci LuminanceHDR
  - cd LuminanceHDR
  - sudo docker run -it -v $(pwd):/sources -e "GIT_BRANCH=master" photoflow/docker-trusty-appimage-base bash /sources/ci/appimage.sh
  - 'if [ -e travis.cancel ]; then
        exit 0;
    fi'
  - bash ci/appimage2.sh

after_success:
    - cd $TRAVIS_BUILD_DIR/LuminanceHDR
    - pwd
    - ls -lh build
    - ls -lh build/out/* # Assuming you have some files in out/ that you would like to upload
    #- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
    - bash  ./upload_rotate.sh "continuous" build/out/* >& /dev/null
    - bash  ./upload_rotate.sh "continuous" $TRAVIS_BUILD_DIR/LuminanceHDR/commit-master.hash >& /dev/null

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

